config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "lists#index"
  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :image

  validates :name, uniqueness: true, presence: true

  DEFAULT_IMG = "https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=987&q=80"
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: :destroy

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      @error = @bookmark.errors.full_messages.first
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @bookmarks = @list.bookmarks
    # empty bookmark for new bookmark form
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  def list_img
    list.image.attached? ? list.image.key : List::DEFAULT_IMG
  end

  private

  def list_params
    params.require(:list).permit(:name, :image)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie, collection: Movie.all.order(:title), prompt: "Pick a movie", input_html: { data: { controller: "slect2" } }   %>
  <%= f.submit %>
  <% if @error %>
    <h5 class="text-warning">
      <%= @error %>
    </h5>
  <% end %>
<% end %>

app/views/bookmarks/new.html.erb
<div class="container bg-dark bg-gradient text-white">
  <h1>Add a Movie</h1>
  <%= render "form", list: @list, bookmark: @bookmark %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body class="bg-dark bg-gradient vh-100">
    <div class="navbar sticky-top navbar-expand-sm navbar-dark bg-dark navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <i class="fa-solid fa-film fs-1"></i>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon "></span>
    </button>

    <div class="collapse navbar-collapse text-white fs-1" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item dropdown">
            <i class="fa-solid fa-bars" class="dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Lists", lists_path, class: "dropdown-item" %>
              <%= link_to "New List", new_list_path, class: "dropdown-item" %>
            </div>
          </li>
          <!--li class="nav-item"-->
          <!--/li-->
      </ul>
    </div>
  </div>
</div>


      <%= yield %>

  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/index.html.erb
<div class="banner_home min-vh-75">
  <div class="container">
    <h1>Movie Lister</h1>
    <p>Make your own watchlists</p>
  </div>
</div>
<div class="container bg-secondary bg-gradient mx-auto mt-3 p-4">
  <div class="d-flex justify-content-between">
    <h3 class="text-white">You have <%= pluralize(@lists.size, "list") %></h3>
    <button type="button" class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#newListModal">
      Create a new list
    </button>
  </div>

  <div class="modal fade" id="newListModal" tabindex="-1" aria-labelledby="newListModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create a new list</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

  <div class="row justify-content-center">
    <% @lists.each do |list| %>
    <div class="col-4">
      <div class="card list-card text-white text-center m-2 border border-dark rounded" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.image.attached? ? cl_image_path(list.image.key) : List::DEFAULT_IMG %>)">
        <div class="card-body">
        <div class="card-title">
          <h5>
            <%= list.name %>
          </h5>
        </div>
        <div class="d-flex justify-content-evenly">
          <%= link_to "See List", list_path(list), class: "btn btn-primary" %>
          <%= link_to list_path(list), data: {turbo_method: :delete, turbo_confirm: "Sure?"}, class: "btn btn-danger text-white" do  %>
          <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>Add a list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :image, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<div class="container d-flex flex-column bg-secondary bg-gradient mt-2">
  <div data-controller="show-new-bookmark" id="data controller">
  <div class="row justify-content-between mt-1">
    <div class="col-6">
      <h1 class="text-white"><%= @list.name %> (<%= pluralize(@list.movies.size, "movie") %>)</h1>
    </div>
        <div class="col-3 mt-2">
          <button class="btn btn-dark" data-action="click->show-new-bookmark#reveal">Add a movie</button>
        </div>
      </div>
      <div data-show-new-bookmark-target="form" class="new_bookmark form-hidden justify-content-center text-white bg-dark bg-gradient border rounded p-0">
        <%= render "bookmarks/form", list: @list, bookmark: @bookmark%>
      </div>
    </div>


  <div class="row justify-content-center">
    <% @bookmarks.each do |bookmark| %>
      <div class="card col-3 p-1 m-1 d-flex flex-column align-items-center justify-content-between">
        <div class="d-flex flex-column align-items-center">
          <h4 class="card-title"><%= bookmark.movie.title %></h4>
          <%= image_tag bookmark.movie.poster_url, class: "w-50 " %>
        </div>
        <div class="mt-1">
          <p><%= bookmark.comment %></p>
        </div>
        <div class="d-flex justify-content-evenly w-100 mt-1">
          <p>Rating: <%= bookmark.movie.rating %></p>
          <%= link_to bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Sure?"} do  %>
          <i class="fa-solid fa-trash"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

</div>